[project]
name = "sentiment-analysis-market"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.3.0",
    "torch>=2.7.1",
    "transformers>=4.52.4",
    "yfinance>=0.2.63",
]
